#https://www.acseo.fr/symfony-acseo-typesense-bundle
acseo_typesense:
    # Typesense host settings
    typesense:
        host: '%env(resolve:TYPESENSE_URL)%'
        key: '%env(resolve:TYPESENSE_KEY)%'
    # Collection settings
    collections:
        papers:                                     
            entity: 'App\Entity\Paper'
            fields: 
                id:
                    name: id
                    type: primary
                name:
                    name: name
                    type: string
                reference: 
                    name: reference
                    type: int32
                quantity:
                    name: quantity
                    type: int32
                createdAt:
                    name: created_at
                    type: datetime
                updatedAt:
                    name: updated_at
                    type: datetime   
                sortable_id:
                    entity_attribute: id           # Entity attribute name forced
                    name: sortable_id
                    type: int32             
            default_sorting_field: sortable_id